
import requests
import json


def get_user():
    base_url = "https://api.github.com/"
    path = "user"
    token = "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"

    headers = {"Authorization": "Bearer {}" .format(token)}

    response = requests.get(base_url + path, headers=headers)
    output = (json.loads(response.text))
    print(output)


# get_user()


def post_repo():
    base_url = "https://api.github.com/"
    path = "user/repos"
    token = "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"

    headers = {"Authorization": "Bearer {}" .format(token)}
    data = {
        "name": "githubnaveen7585",
        "description": "generated by api"
    }
    response = requests.post(base_url + path, headers=headers, json=data)
    # assert response.status_code == 201
    print(response.json())


post_repo()


def delete_repo():
    base_url = "https://api.github.com/"
    path = "repos/NaveenTestopenshift/githubnaveen7585"
    token = "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"

    headers = {"Authorization": "Bearer {}" .format(token)}
    response = requests.delete(base_url + path, headers=headers)
    # print(response.text)


# delete_repo()

def update_repo():
    base_url = "https://api.github.com/"
    path = "repos/NaveenTestopenshift/githubnaveen8383"
    token = "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"
    data = {"name": "githubnaveen8484"}

    headers = {"Authorization": "Bearer {}" .format(token)}
    response = requests.patch(base_url + path, headers=headers, json=data)
    json_data = response.json()
    print(json_data)


update_repo()




